version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: sa
    networks:
      - backend
networks:
  backend: